export { default as Blob } from "./Blob/Blob";
export { default as Contacts } from "./Contacts/Contacts";
export { default as Container } from "./Container/Container";
export { default as GradientButton } from "./GradientButton/GradientButton"
export { default as Logotype } from "./Logotype/Logotype";
export { default as Modal } from "./Modal/Modal";
export { default as Provider } from "./Provider/Provider";
export { default as Section } from "./Section/Section";
export { default as TransparentButton } from "./TransparentButton/TransparentButton";